# Python versions for matrix
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# Django versions for matrix
env:
  - DJANGO_VERSION=1.8.18
  - DJANGO_VERSION=1.10.7
  - DJANGO_VERSION=1.11.4

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -q Django==$DJANGO_VERSION --quiet
  - pip install coveralls

# Command to run tests, e.g. python setup.py test
script:
  - coverage run --source=highlightjs manage.py test

# Report to coveralls
after_success:
  - coveralls
