name: CI

on:
  create:
    tags:
      - "*" # run on all tags
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        django-version: ["4.0", "4.1", "4.2", "5.0"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache Poetry virtual environment
        id: poetry-cache
        uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-${{ matrix.python-version }}-poetry-v1-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-v1-
      - name: Install Poetry
        run: pip install poetry
      - name: Set poetry to use virtualenvs.in-project true
        run: |
          poetry config virtualenvs.in-project true
      - name: Install dependencies
        run: |
          poetry install --with dev
      - name: Install Django
        run: |
          poetry run pip install django~=${{ matrix.django-version }}
      - name: Cache pre-commit hooks
        if: matrix.python-version == '3.11' && matrix.django-version == '5.0'
        id: pre-commit-cache
        uses: actions/cache@v2
        with:
          path: $HOME/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-hooks-${{ hashFiles('**/.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-hooks-
      - name: Run pre-commit
        if: matrix.python-version == '3.11' && matrix.django-version == '5.0'
        run: |
          poetry run pre-commit run --all-files
      - name: Run tests and coverage
        run: |
          poetry run coverage run --source=highlightjs manage.py test
          # output coverage report
          poetry run coverage report
      - name: Publish coverage
        # only run on python 3.11 and django 5.0
        # no need to publish coverage for all python and django versions
        if: matrix.python-version == '3.11' && matrix.django-version == '5.0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: poetry run coveralls
      - name: Publish package
        if: matrix.python-version == '3.11' && matrix.django-version == '5.0' && startsWith(github.ref, 'refs/tags')
        run: |
          echo "Publishing package to PyPI"
          echo "poetry version: $(poetry --version)"
          poetry build
          poetry publish --username=__token__ --password=${{ secrets.PYPI_SECRET }}
