name: CI

on:
  create:
    tags:
      - "*" # run on all tags
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        django-version: ["4.2", "5.0", "5.1"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install dependencies
        run: |
          uv sync --locked --all-extras --dev
      - name: Install Django
        run: |
          uv run pip install django~=${{ matrix.django-version }}
      - name: Cache pre-commit hooks
        if: matrix.python-version == '3.13' && matrix.django-version == '5.1'
        id: pre-commit-cache
        uses: actions/cache@v4
        with:
          path: $HOME/.cache/pre-commit
          key: ${{ runner.os }}-${{ matrix.python-version }}-pre-commit-hooks-${{ hashFiles('**/.pre-commit-config.yaml') }}
      - name: Run pre-commit
        if: matrix.python-version == '3.13' && matrix.django-version == '5.1'
        run: |
          uv run pre-commit run --all-files
        env:
          PRE_COMMIT_HOME: $HOME/.cache/pre-commit
      - name: Run tests and coverage
        run: |
          uv run coverage run --source=highlightjs manage.py test
          # output coverage report
          uv run coverage report
          # output coverage report in xml format
          uv run coverage xml
      - name: Publish coverage
        if: matrix.python-version == '3.13' && matrix.django-version == '5.1'
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish package
        if: matrix.python-version == '3.13' && matrix.django-version == '5.1' && startsWith(github.ref, 'refs/tags')
        run: |
          echo "Publishing package to PyPI"
          echo "poetry version: $(poetry --version)"
          uv build
          uv publish --username=__token__ --password=${{ secrets.PYPI_SECRET }}
      - name: Minimize uv cache
        run: uv cache prune --ci
